### ISSUE TITLE
[BUG] cant remove some wall top lists

### ISSUE THREAD

**Issue by rodopoulos1** [K4ryuu/K4-System-WallToplist#1]
i cant remove some wall top lists

![image](https://github.com/K4ryuu/K4-System-WallToplist/assets/101236856/7ec99694-bd0b-4216-b9a7-05737a0e2951)

**Comment by M-archand** [comment]
Hi @K4ryuu, I updated to the latest version 1.0.3 (& using the latest K4-WorldText-API) but I am still having this same issue. It will be removed from the over-world but it isn't removed from the json file.

**Comment by M-archand** [comment]
I should also add that I am experiencing three different things:

- It will work fine on the first try. 
- It will remove it from the over-world but not the json. 
- It will remove it from json, but not the over-world, and I have to type the removal command a second time for it to be removed from the over-world.
